[P3_lookup_tables]
git-tree-sha1 = "4b8a8131a2d919e441f3ed745fe35bfee3009872"
lazy = true

    [[P3_lookup_tables.download]]
    sha256 = "d81442098b7c250842afc795d21295f44c8ef9e5957db5a76c156516cc76c65c"
    url = "https://github.com/NumericalEarth/Breeze.jl/releases/download/P3_lookup_tables_v1.0/P3_lookup_tables.tar.gz"

[cloud_les_library]
git-tree-sha1 = "c01b914c0bf561292bac0b5b55cd02a3ba57e9c2"
lazy = true

    [[cloud_les_library.download]]
    sha256 = "899d68c04a634b5fe82a857b5a3eaeb04ed3befa252a70d978fe6462fbaa99d0"
    url = "https://github.com/NumericalEarth/Breeze.jl/releases/download/cloud_les_library_v1.0/cloud_les_library.tar.gz"
