[P3_lookup_tables]
git-tree-sha1 = "4b8a8131a2d919e441f3ed745fe35bfee3009872"
lazy = true

    [[P3_lookup_tables.download]]
    sha256 = "d81442098b7c250842afc795d21295f44c8ef9e5957db5a76c156516cc76c65c"
    url = "https://github.com/NumericalEarth/Breeze.jl/releases/download/P3_lookup_tables_v1.0/P3_lookup_tables.tar.gz"

[shen_et_al_2022_les_profiles]
git-tree-sha1 = "ee49d42fe593873d4bc5570a97309d421e2b6963"
lazy = true

    [[shen_et_al_2022_les_profiles.download]]
    sha256 = "135cbec0f82a42126af9716d202ea575d1d6ee83a69f3ca44873cb94fcd294cc"
    url = "https://github.com/NumericalEarth/Breeze.jl/releases/download/shen_et_al_2022_les_profiles_v1.0/shen_et_al_2022_les_profiles.tar.gz"
