name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

env:
  # Don't make Reactant occupy all the GPU memory
  XLA_REACTANT_GPU_PREALLOCATE: 'false'
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: 'eager'

jobs:
  check-files:
    name: Check for modified files
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      files: ${{ steps.filter.outputs.files }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            files:
              - ".github/workflows/CI.yml"
              - "ext/**"
              - "src/**"
              - "test/**"
              - "Project.toml"

  test:
    needs: check-files
    if: ${{ needs.check-files.outputs.files == 'true' }}
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - check-bounds ${{ matrix.check-bounds }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 75
    container:
      image: ${{ (startsWith(matrix.os, 'aws-linux-nvidia-gpu-') && format('ghcr.io/numericalearth/breeze-docker-images:test-julia_{0}', matrix.version) ) || '' }}
      options: --gpus=all
      volumes:
        # Mount host `/usr/local` so that we can delete some stuff afterwards
        - /usr/local:/host-usr-local
    strategy:
      fail-fast: false
      matrix:
        version:
          - "min"
          - "1.12.6"
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - "default"
        check-bounds:
          - "yes"
        exclude:
          - version: "min"
            os: windows-latest
        include:
          # `--check-bounds=auto` is necessary for testing Reactant workloads
          # until https://github.com/EnzymeAD/Reactant.jl/issues/2347 is fixed.
          - version: "1.12.6"
            os: aws-linux-nvidia-gpu-l4-4xl
            arch: "default"
            check-bounds: "auto"
          - version: "1.11.9"
            os: aws-linux-nvidia-gpu-l4-4xl
            arch: "default"
            check-bounds: "auto"
    steps:
      - name: df before cleanup
        if: ${{ startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        run: |
          df -hT
      - name: Clean up old CUDA toolkits
        if: ${{ startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        # Save storage by deleting old CUDA toolkits, we'll use v13
        run: |
          rm -rf /host-usr-local/cuda-12.*
      - name: df after cleanup
        if: ${{ startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        run: |
          df -hT
      - name: "Check out repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: "Install Julia"
        uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        # On the self-hosted GPU runners we use a Docker image with Julia pre-installed.
        if: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Show versioninfo
        if: ${{ startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        run: |
          julia --compile=min -O0 -e 'using InteractiveUtils; versioninfo()'
      - name: "Cache Julia depot"
        uses: julia-actions/cache@a45e8fa8be21c18a06b7177052533149e61e9b38 # v3.1.0
        with:
          # On self-hosted runners we use the prebuilt Docker container, which already
          # caches pkgimages and such, so we don't need to cache here most things.  Only
          # useful thing is the scratchspaces, in particular ParallelTestRunner's to make
          # scheduling of test jobs more efficients.
          cache-artifacts: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
          cache-packages: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
          cache-registries: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
          cache-compiled: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
          cache-scratchspaces: true
          cache-logs: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
      - name: "Set test arguments and other environment variables"
        shell: bash
        run: |
          # Run tests in verbose mode
          TEST_ARGS=(--verbose)
          # Exit immediately if there's a test failure
          TEST_ARGS+=(--quickfail)

          if [[ ${{ matrix.os }} == *linux-nvidia-gpu* ]]; then
              # When running the tests on a GPU node we always want to make sure
              # CUDA is functional.
              echo "BREEZE_ENSURE_CUDA_FUNCTIONAL=true" | tee -a "${GITHUB_ENV}"
              # In Julia v1.12+, use multiple GC threads.
              echo "JULIA_NUM_GC_THREADS=4,1" | tee -a "${GITHUB_ENV}"
              # On the GPU runners we sometimes run out-of-memory because we have several
              # concurrent jobs, some of them reaching a large memory usage.  We reduce the
              # number of jobs to avoid memory issues.
              TEST_ARGS+=(--jobs=$(($(nproc) - 1)))
          fi

          if [[ ${{ runner.os }} == "macOS" ]]; then
              # On macOS runners, `Metal.functional()` returns `false` because the GPU is
              # virtualised, but we should be able to actually use it anyway.
              echo "BREEZE_FORCE_METAL_FUNCTIONAL=true" | tee -a "${GITHUB_ENV}"
              # Encourage ParallelTestRunner to use multiple jobs on macOS, rather
              # than the single one it'd use by default.
              TEST_ARGS+=(--jobs=2)
          fi
          echo "runtest_test_args=${TEST_ARGS[@]}" | tee -a "${GITHUB_ENV}"
      - name: Install earlyoom
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          sudo apt-get install -y earlyoom
      - name: Prepare test environment
        if: ${{ startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        shell: bash
        run: |
          # Running doctests need to run `git` commands in this directory, but `git`
          # complains about dubious ownership when using the Docker image.
          git config --global --add safe.directory ${PWD}

          # Little complication: we built the Docker images on a non-GPU system and so we
          # had to use a `LocalPreferences.toml` file to force the CUDA runtime, but this
          # means that we have to use the same preferences also for the tests environment,
          # because running the tests clears up the load path.  Let's copy the global
          # preference file to test directory (the global one will be ignored during the
          # tests).
          cp -v /usr/local/share/julia/environments/breeze/LocalPreferences.toml test/.
      - name: Instantiate test environment
        timeout-minutes: 30
        shell: bash
        run: |
          julia --project=test --color=yes --check-bounds=${{ matrix.check-bounds }} -e '
          using Pkg;
          Pkg.instantiate()
          '
      - name: Run tests
        shell: bash
        env:
          XLA_FLAGS: '--xla_disable_hlo_passes=multi_output_fusion'
        run: |
          if [[ ${{ runner.os }} == 'Linux' ]]; then
              # We use earlyoom only on the Linux machines
              earlyoom -m 3 -s 100 -r 300 --prefer 'julia' &
          fi

          export TMPDIR="${{ github.workspace }}/tmp"
          mkdir -vp "${TMPDIR}"

          julia --project --color=yes --check-bounds=${{ matrix.check-bounds }} -e 'using Pkg; Pkg.test(; coverage=true, julia_args=["--check-bounds=${{ matrix.check-bounds }}", "--compiled-modules=yes", "--depwarn=yes", "-O0"], test_args=`${{ env.runtest_test_args }}`, force_latest_compatible_version=false, allow_reresolve=true)'
      - name: "Upload Manifest"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        timeout-minutes: 2
        with:
          name: manifest-${{ matrix.version }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.check-bounds }}
          path: '**/Manifest*.toml'
          retention-days: 90
          overwrite: false
      - name: "Upload Reactant MLIR dumps as artifacts"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: mlir-dumps-${{ matrix.version }}-${{ matrix.os }}
          path: ${{ github.workspace }}/tmp/
          if-no-files-found: ignore
          retention-days: 7
      - name: "Process Julia coverage files"
        uses: julia-actions/julia-processcoverage@03114f09f119417c3242a9fb6e0b722676aedf38 # v1.2.2
      - name: "Upload coverage data to CodeCov"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
        continue-on-error: true

  # Fake test job, to launch when no relevant files are modified: we need this is launch a
  # job with the required name, even when we don't actually want to run CI.
  fake-test:
    needs: check-files
    if: ${{ needs.check-files.outputs.files != 'true' }}
    # The name must exactly match the required job.
    name: Julia ${{ matrix.fake-version }} - ${{ matrix.fake-os }} - ${{ matrix.fake-arch }} - check-bounds ${{ matrix.fake-check-bounds }} - ${{ github.event_name }}
    runs-on: ${{ matrix.fake-os }}
    timeout-minutes: 1
    strategy:
      # NOTE: we use a one-element matrix, instead of just hardcoding the expected name
      # above, because when this job is to be skipped, we don't want this to have the name
      # fully resolved, otherwise it may accidentally make the PR mergeable when it
      # shouldn't (the `${{ matrix.... }}` in the job name are resolved only when the job is
      # actually launched).
      matrix:
        include:
          - fake-version: "min"
            fake-os: ubuntu-latest
            fake-arch: "default"
            fake-check-bounds: "yes"
    steps:
      - name: "Run fake tests"
        run: |
          true
