name: Validation

on:
  push:
    branches:
      - "main"
    paths: &paths
      - ".github/workflows/Validation.yml"
      - "examples/Project.jl"
      - "examples/boussinesq_bomex.jl"
      - "ext/**"
      - "src/**"
      - "Project.toml"
  pull_request:
    paths: *paths
  release:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

env:
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: 'eager'

jobs:
  validate:
    name: Validation - Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.12.6"
        os:
          - ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Install Julia"
        uses: julia-actions/setup-julia@4c0cb0fce8556fdb04a90347310e5db8b1f98fb9 # v2.7.0
        with:
          version: ${{ matrix.version }}
      - name: "Cache Julia depot"
        uses: julia-actions/cache@a45e8fa8be21c18a06b7177052533149e61e9b38 # v3.1.0
      - name: Instantiate examples environment
        shell: julia --color=yes --project=examples {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Run BOMEX example
        env:
          VALIDATION: "true"
          CI: "true"
        run: |
          julia --color=yes --project=examples examples/boussinesq_bomex.jl
      - name: "Upload Manifest"
        if: always()
        timeout-minutes: 2
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: manifest
          path: '**/Manifest*.toml'
          retention-days: 90
